### ISSUE TITLE
建议支持 javadoc-tool

### ISSUE THREAD

**Issue by xfcode-projects** [ysdxz207/dockit#2]
规范地址：https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html

**Comment by ysdxz207** [comment]
dockit和使用官方javadoc tool不冲突的，你仍然可以使用javadoc tool去生成官方的文档。但是如果你想用javadoc tool的规范来生成markdown文档的话我最早是考虑过的，为了不和官方的发生冲突才自己定义了一套生成方案。
